### ISSUE TITLE
Does not bring Fb data from facebook page

### ISSUE THREAD

**Issue by mustafakhalidcs** [mikahanninen/grav-plugin-facebook#20] opened 2017-03-14 10:03 UTC
I've configured my facebook plugin and embedded my fb app id and secret. but the plugin does not pulling up the data from that page. Instead I am getting this text on my page 
{{ facebook_posts() }}

Please guide me if I am doing anyting wrong. 

Best

**Comment by gillesthoma** [comment] 2017-03-19 01:13
Hi,
I have the same issue as mustafakhalidcs. I simply created a page and than added the shortcode to the content.
Where exactly do we have to put the shortcode?

Regards,
Gilles Thoma

**Comment by mikahanninen** [comment] 2017-03-19 08:01
It seems that you have correct code in the page 

`{{ facebook_posts() }}`

Can you check that your configuration contains...
1. Post settings - Posts page ID at least
2. Application ID and Application secret
3. Make sure that Plugin is enabled
4. Check if logs/grav.log file contains any errors or info related Facebook

I will try to reproduce your problem.

**Comment by gillesthoma** [comment] 2017-03-19 10:04
I checked all the settings and they should be correct. Nothing in the log file.
It seems that the code is not rendered as code but as simple text.

I have the basic core + admin installed. I added the facebook plugin via the integrated plugin manager.

Am I missing something?

Thanks for your help,
Gilles Thoma

**Comment by mikahanninen** [comment] 2017-03-19 10:14
I think I found the reason your problem, maybe. You need to make sure that you have checked option "Process Twig" in the System Configuration page or in the Advanced section of the Page where you have the shortcode.

**Comment by mikahanninen** [comment] 2017-03-20 09:27
Did you get the issue fixed ?

**Comment by gillesthoma** [comment] 2017-03-20 10:04
Hey Mika,

it's working now! You were right. I had to check "Process Twig" in the configuration.

Thanks alot!
Cheers

**Comment by mikahanninen** [comment] 2017-03-20 10:15
Excellent! I will close this issue.

**Closed as completed by mikahanninen** 2017-03-20 10:15 UTC
